apiVersion: apps/v1
kind: Deployment
metadata:
  name: colordemo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colordemo
  template:
    metadata:
      labels:
        app: colordemo
    spec:
      containers:
      - name: colordemo
        image: kimbahir/colordemo:v10
---
apiVersion: v1
kind: Service
metadata:
  name: colordemo 
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: colordemo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colordemo
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
  - host: "demo.proficio.dk"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: colordemo
              port:
                number: 80